name: release

on:
  release:
    types: [released]

permissions:
  contents: read
  packages: write

jobs:
  docker-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  push-tunneld:
    runs-on: ubuntu-latest
    needs: docker-setup
    steps:
      - name: Build and push tunneld
        uses: docker/build-push-action@v6
        with:
          file: ./build/tunneld/Dockerfile
          push: true
          tags: ghcr.io/rhermens/tunneld:${{ github.event.release.tag_name }},ghcr.io/rhermens/tunneld:latest
  push-tunnel-client:
    runs-on: ubuntu-latest
    needs: docker-setup
    steps:
      - name: Build and push client
        uses: docker/build-push-action@v6
        with:
          file: ./build/tunnel/Dockerfile
          push: true
          tags: ghcr.io/rhermens/tunnel:${{ github.event.release.tag_name }},ghcr.io/rhermens/tunnel:latest
