name: release

on:
  release:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push tunneld
        uses: docker/build-push-action@v6
        with:
          file: ./build/tunneld/Dockerfile
          push: true
          tags: ghcr.io/rhermens/tunneld:latest
      - name: Build and push client
        uses: docker/build-push-action@v6
        with:
          file: ./build/tunnel/Dockerfile
          push: true
          tags: ghcr.io/rhermens/tunnel:latest
