name: release

on:
  release:
    types: [released]

jobs:
  docker-setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

  release-tunneld:
    runs-on: ubuntu-latest
    needs: [docker-setup]
    permissions:
      packages: write
    steps:
    - name: Build and push tunneld
      uses: docker/build-push-action@v6
      with:
        file: ./build/tunneld/Dockerfile
        push: true
        tags:
          - ghcr.io/rhermens/tunneld:${{ github.event.release.tag_name }}
          - ghcr.io/rhermens/tunneld:latest
  release-tunnel-client:
    runs-on: ubuntu-latest
    needs: [docker-setup]
    permissions:
      packages: write
    steps:
    - name: Build and push client
      uses: docker/build-push-action@v6
      with:
        file: ./build/tunnel/Dockerfile
        push: true
        tags:
          - ghcr.io/rhermens/tunnel:${{ github.event.release.tag_name }}
          - ghcr.io/rhermens/tunnel:latest
